### ISSUE TITLE
errors in run example

### ISSUE THREAD

**Issue by nanomolar** [Rose-STL-Lab/FS-CAP#3]
root@a62e8684d434:/# python score_compounds.py --context_smiles "CCC;CCCC;CCCCC" --context_activities "1000;1;10" --query_smiles "CCCCCCCC;CCCCCCCCC" --model_file ./model.pt --encoding_dim 512
Traceback (most recent call last):
  File "//score_compounds.py", line 66, in <module>
    fscap = FSCAP(args.model_file)
  File "//score_compounds.py", line 16, in __init__
    self.context_encoder = MLPEncoder(2048, config).to(device)
  File "/models.py", line 8, in __init__
    if config['encoder_batchnorm']:
KeyError: 'encoder_batchnorm'

**Comment by Tong-Du** [comment]
try change `config = {'encoding_dim': args.encoding_dim}` in file `score_compounds.py`(Line 65) to 

```python
config = {
    'encoding_dim': args.encoding_dim,
    'encoder_batchnorm':True,
    'pred_batchnorm': False,
    'layer_width':2048,
    'd_model':512,
    'pred_dropout': True,
    'pred_dropout_p': 0.1,
}
```
It work  for me.
